name: deploy sam

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # checkout
      - name: Checkout Code
        uses: actions/checkout@v3
      
      
      # endre mappe
      - name: Change directory to application folder
        working-directory: sam_lambda/sam-app

      # python 
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # sam cli
      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      # access keys
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1 

      # build
      - name: Build SAM Application
        run: |
          sam build

      # deploy
      - name: Deploy SAM Application
        run: |
          sam deploy --no-confirm-changeset --capabilities CAPABILITY_IAM --stack-name sam-app --region eu-west-1
